apiVersion : apps/v1
kind: Deployment
metadata:
  name: kimthpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimthpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: kimthpipelinesjavascriptdocker 
    spec:
      containers:
        - name: kimthpipelinesjavascriptdocker 
          image: kimthskmycontainerregistry.azurecr.io/kimthpipelinesjavascriptdocker
          ports:
          - containerPort: 8080